### ISSUE TITLE
Cannot run the code of CP_MAP

### ISSUE THREAD

**Issue by Charlie0257** [hyperplane-lab/RLAfford#2]
When I tried the command of CP MAP in Experiments.MD, there is an error occurring:

`*** Failed to load 'assets/franka_description/robots/franka_panda_slider_longer.urdf'[Error] [carb.gym.plugin] Failed to parse URDF file 'franka_description/robots/franka_panda_slider_longer.urdf'
[Error] [carb.gym.plugin] Failed to import URDF file 'franka_description/robots/franka_panda_slider_longer.urdf'
[Error] [carb.gym.plugin] *** Failed to load 'franka_description/robots/franka_panda_slider_longer.urdf' from 'assets'`

`Traceback (most recent call last):
  File "train.py", line 69, in <module>
    train()
  File "train.py", line 48, in train
    task, env = parse_task(args, cfg, cfg_train, sim_params, agent_index, logdir)
  File "/home/charlie/PycharmProjects/RLAfford/MARL_Module/envs/utils/parse_task.py", line 88, in parse_task
    log_dir=log_dir)
  File "/home/charlie/PycharmProjects/RLAfford/MARL_Module/envs/tasks/franka_cabinet_PC_partial_cp_map.py", line 16, in __init__
    super().__init__(cfg, sim_params, physics_engine, device_type, device_id, headless, agent_index, is_multi_agent, log_dir=log_dir)
  File "/home/charlie/PycharmProjects/RLAfford/MARL_Module/envs/tasks/franka_cabinet_PC_partial.py", line 27, in __init__
    super().__init__(cfg, sim_params, physics_engine, device_type, device_id, headless, log_dir=log_dir)
  File "/home/charlie/PycharmProjects/RLAfford/MARL_Module/envs/tasks/franka_cabinet.py", line 100, in __init__
    super().__init__(cfg=self.cfg, enable_camera_sensors=cfg["env"]["enableCameraSensors"])
  File "/home/charlie/PycharmProjects/RLAfford/MARL_Module/envs/tasks/hand_base/base_task.py", line 90, in __init__
    self.create_sim()
  File "/home/charlie/PycharmProjects/RLAfford/MARL_Module/envs/tasks/franka_cabinet.py", line 230, in create_sim
    self._place_agents(self.cfg["env"]["numTrain"]+self.cfg["env"]["numVal"], self.cfg["env"]["envSpacing"])
  File "/home/charlie/PycharmProjects/RLAfford/MARL_Module/envs/tasks/franka_cabinet.py", line 559, in _place_agents
    self._load_franka(env_ptr, env_id)
  File "/home/charlie/PycharmProjects/RLAfford/MARL_Module/envs/tasks/franka_cabinet.py", line 289, in _load_franka
    self.franka_left_finger_pc = torch.load(os.path.join(self.asset_root, "franka_description/point_cloud/left_finger_long"), map_location=self.device)
  File "/home/charlie/anaconda3/envs/rlgpu/lib/python3.7/site-packages/torch/serialization.py", line 699, in load
    with _open_file_like(f, 'rb') as opened_file:
  File "/home/charlie/anaconda3/envs/rlgpu/lib/python3.7/site-packages/torch/serialization.py", line 231, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/charlie/anaconda3/envs/rlgpu/lib/python3.7/site-packages/torch/serialization.py", line 212, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: 'assets/franka_description/point_cloud/left_finger_long'`

It seems no such files in the uploaded dataset (i.e., I only found the information of objects:(

Thanks for any help! :) @boshi-an

**Comment by boshi-an** [comment]
Sorry for that! I will check the assets and upload a new one soon.Sent from my iPadOn Feb 23, 2023, at 4:33 PM, Charlie0257 ***@***.***> wrote:﻿
When I tried the command of CP MAP in Experiments.MD, there is an error occurring:
*** Failed to load 'assets/franka_description/robots/franka_panda_slider_longer.urdf'[Error] [carb.gym.plugin] Failed to parse URDF file 'franka_description/robots/franka_panda_slider_longer.urdf' [Error] [carb.gym.plugin] Failed to import URDF file 'franka_description/robots/franka_panda_slider_longer.urdf' [Error] [carb.gym.plugin] *** Failed to load 'franka_description/robots/franka_panda_slider_longer.urdf' from 'assets'
Traceback (most recent call last): File "train.py", line 69, in <module> train() File "train.py", line 48, in train task, env = parse_task(args, cfg, cfg_train, sim_params, agent_index, logdir) File "/home/charlie/PycharmProjects/RLAfford/MARL_Module/envs/utils/parse_task.py", line 88, in parse_task log_dir=log_dir) File "/home/charlie/PycharmProjects/RLAfford/MARL_Module/envs/tasks/franka_cabinet_PC_partial_cp_map.py", line 16, in __init__ super().__init__(cfg, sim_params, physics_engine, device_type, device_id, headless, agent_index, is_multi_agent, log_dir=log_dir) File "/home/charlie/PycharmProjects/RLAfford/MARL_Module/envs/tasks/franka_cabinet_PC_partial.py", line 27, in __init__ super().__init__(cfg, sim_params, physics_engine, device_type, device_id, headless, log_dir=log_dir) File "/home/charlie/PycharmProjects/RLAfford/MARL_Module/envs/tasks/franka_cabinet.py", line 100, in __init__ super().__init__(cfg=self.cfg, enable_camera_sensors=cfg["env"]["enableCameraSensors"]) File "/home/charlie/PycharmProjects/RLAfford/MARL_Module/envs/tasks/hand_base/base_task.py", line 90, in __init__ self.create_sim() File "/home/charlie/PycharmProjects/RLAfford/MARL_Module/envs/tasks/franka_cabinet.py", line 230, in create_sim self._place_agents(self.cfg["env"]["numTrain"]+self.cfg["env"]["numVal"], self.cfg["env"]["envSpacing"]) File "/home/charlie/PycharmProjects/RLAfford/MARL_Module/envs/tasks/franka_cabinet.py", line 559, in _place_agents self._load_franka(env_ptr, env_id) File "/home/charlie/PycharmProjects/RLAfford/MARL_Module/envs/tasks/franka_cabinet.py", line 289, in _load_franka self.franka_left_finger_pc = torch.load(os.path.join(self.asset_root, "franka_description/point_cloud/left_finger_long"), map_location=self.device) File "/home/charlie/anaconda3/envs/rlgpu/lib/python3.7/site-packages/torch/serialization.py", line 699, in load with _open_file_like(f, 'rb') as opened_file: File "/home/charlie/anaconda3/envs/rlgpu/lib/python3.7/site-packages/torch/serialization.py", line 231, in _open_file_like return _open_file(name_or_buffer, mode) File "/home/charlie/anaconda3/envs/rlgpu/lib/python3.7/site-packages/torch/serialization.py", line 212, in __init__ super(_open_file, self).__init__(open(name, mode)) FileNotFoundError: [Errno 2] No such file or directory: 'assets/franka_description/point_cloud/left_finger_long'
It seems no such files in the uploaded dataset (i.e., I only found the information of objects:(
Thanks for any help! :) @boshi-an

**Comment by boshi-an** [comment]
Fixed! Thanks for your patience!

**Comment by Charlie0257** [comment]
Thanks a lot! :)
